<DSP> Adding support for DSP
akashkollipara/cyancore pull request #25
Opened 2021-08-02 08:46 UTC by akashkollipara

---
* First commit for DSP support on Cyancore
* Added convolution function

2021-08-02 08:58 UTC, pranjalchanda08 requested changes

2021-08-02 08:58 UTC, pranjalchanda08 commented on src/lib/libnmath/dsp/conv.c
> +status_t __conv(float *a, int size_a, float *b, int size_b, float *c, int size_c)
Place function headers for better usage understanding.

2021-08-02 18:28 UTC, akashkollipara commented on src/lib/libnmath/dsp/conv.c
> +status_t __conv(float *a, int size_a, float *b, int size_b, float *c, int size_c)
made changes in a5b81b4

2021-08-03 12:03 UTC, pranjalchanda08 approved these changes

2021-08-03 15:22 UTC, pranjalchanda08 commented
Merging PR as all the review comments are taken care of.

2021-08-03 15:22 UTC, merged